### ISSUE TITLE
Katex instead of MathJax?

### ISSUE THREAD

**Issue by thorstink** [jxxcarlson/elm-markdown#1]
Hi! 

I wondered whether you considered using [Katex](https://katex.org/) for this package? It renders most math quite a bit faster than Mathjax last time I checked. 

I'm a super-starter at elm so I'm not sure yet if it is straightforward to swap it out / alternate between the two? :-)

Cheers

**Comment by jxxcarlson** [comment]
Thanks for your comment. Haven't looked at it yet -- don't know to what extent it is compatible with Elm.  At the moment I am looking at MathJax 3, which was recently released. It is much faster than the previous version and has various other improvements as well. Will look into it when I get a chance to do so.
