### ISSUE TITLE
.pdf generation

### ISSUE THREAD

**Issue by saulius-krasuckas** [jxxcarlson/elm-markdown#21]
Can this software generate .pdf file already?
If not, how can I contribute?

**Comment by jxxcarlson** [comment]
I render markdown in https://minilatex.lamdera.app by first converting it to MiniLaTeX, then to PDF.  If you have a good way to do it separately, that of course would be wonderful.  


— Jim

**Comment by saulius-krasuckas** [comment]
OK, I entered the following code in this app:
```
# test2

My simple list:

- hello
- Moto
___

And the formula:

$ i_2 \cdot y_3 = \frac{1}{x+2} $
```

What I get here is:

![image](https://user-images.githubusercontent.com/74717106/105558772-0b975f00-5d18-11eb-9308-7164765b393b.png)

What should be my next steps towards .pdf generation?

**Comment by saulius-krasuckas** [comment]
Actually https://markdown.minilatex.app/ has some issues. LaTeX formulas here are rendered wrongly:

![image](https://user-images.githubusercontent.com/74717106/105559316-7f863700-5d19-11eb-98a9-725e8377de43.png)
---

Thus I am used to your other web-app: [jxxcarlson/markdown-demo](https://github.com/jxxcarlson/markdown-demo):

![image](https://user-images.githubusercontent.com/74717106/105559475-eefc2680-5d19-11eb-93e2-53f32cd6f12c.png)

... which renders LaTeX parts OK.

Would that make any difference for me in .pdf file generation?
(should I decide to use the latter app)

PS. I might create the issue in the latter repo if needed.

**Comment by jxxcarlson** [comment]
Hello!

You are signed in as guest.  To generate PDF you need a regular account —
Just refresh your browser, then go through the signup process.  As a signed-in
user, you will find a “PDF” button in the footer.

**Comment by saulius-krasuckas** [comment]
Thanks, I am still interested in the details of .pdf file generation. 
The FAQ writes:

> All of the code in the two compilers, MiniLaTeX to Html and Math-Markdown to Html, is written in Elm, a statically typed functional language. The minilatex.lamdera.app is also written in Elm using Lamdera, a system that allows one to write both the front and backend of the app in the same language. The front and backend parts of the app communicate via websockts, making performance especially snappy.

But there is no mention about the steps to generate a .pdf . Is it done by the frontend or the backend at the very least?

I am not even sure what is the exact source of this app! Is it that by a chance:
https://github.com/jxxcarlson/lamdera-minilatex ?

**Comment by jxxcarlson** [comment]
The PDF file is generated by a standalone server that does just one thing: generate pdf files.

The server is a 117-line Haskell program which uses the Scotty library.

PDF files for MiniLaTeX are generated by first using Elm to derive a standard LaTeX document with 
\begin{document}, inclusion of various packages, etc..  This document is sent to the PDF server.

Markdown files are first translated by an Elm function into LaTeX and the previous process is repeated.

The Markdown-to-LaTeX translation needs more work.

Best regards,

Jim Carlson

PS.  Yes, the app in question is https://github.com/jxxcarlson/lamdera-minilatex <https://github.com/jxxcarlson/lamdera-minilatex> . Still a work-in-progress,
But getting there.  I appreciate your error report.

**Comment by saulius-krasuckas** [comment]
Thanks James. It looks like it launches `xelatex` internally. 
I will need to find a quick way to generate a .pdf from my sources on GitHub.

There is a lot for me to learn regarding web apps and specifically integration with GitHub.

I think the issue should be closed, right?
